//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Mart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Buyer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buyer()
        {
            this.Orders = new HashSet<Order>();
        }

        public int BuyerID { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Buyer Name: ")]
        [StringLength(40, ErrorMessage = "Name can be atmost 40 characters!")]
        public string BuyerName { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "E-mail: ")]
        public string BuyerEmail { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password: ")]
        [MaxLength(12, ErrorMessage = "Password can be atmost 12 characters!")]
        [MinLength(6, ErrorMessage = "Password can be atmost 6 characters!")]
        public string BuyerPassword { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Retype Password: ")]
        public string ConfirmBuyerPassword { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Mobile No.: ")]
        [MaxLength(11, ErrorMessage = "Mobile No. can be atmost 11 characters!")]
        [MinLength(11, ErrorMessage = "Mobile No. can be atleast 11 characters!")]
        public string BuyerPhone { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Address: ")]
        [StringLength(100, ErrorMessage = "Address can be atmost 100 characters!")]
        public string BuyerAdress { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Date of Birth: ")]
        public Nullable<System.DateTime> BuyerDOB { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
