//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Mart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {

        public int OrderID { get; set; }
        public int SellerID { get; set; }
        public int BuyerID { get; set; }
        public int ProductID { get; set; }
        public int AdminID { get; set; }
        [Required]
        [Range(1, 100, ErrorMessage = "Quantity must be from 1-100")]
        public int OrderQuantity { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Order Date")]
        public System.DateTime OrderDate { get; set; }

       

        public Nullable<int> OrderStatus { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Buyer Buyer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
