//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Mart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Hass = new HashSet<Has>();
            this.Orders = new HashSet<Order>();
        }

        public int ProductID { get; set; }


        public int CategoryID { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Product Name")]
        [StringLength(40, ErrorMessage = "Name can be atmost 40 characters!")]
        public string ProductName { get; set; }
        [Required]
        
        [Display(Name = "Product Price")]
        public decimal ProductPrice { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Product Details")]
        [StringLength(200, ErrorMessage = "Product details can be atmost 200 characters!")]
        public string ProductDescription { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Product Category")]
        [StringLength(40, ErrorMessage = "Product Category can be atmost 40 characters!")]


        public string ProductCategory { get; set; } = "N/A";
        public Nullable<decimal> ProductRating { get; set; }
        [Required]
        [DataType(DataType.ImageUrl)]
        [Display(Name = "Product Image")]
        public string ProductIMG { get; set; }


        public HttpPostedFileBase ImageFile { get; set; }


        

        public Nullable<int> ProductStatus { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Has> Hass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
